catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade

catalogs:
  dev:
    '@eslint/config-inspector': ^3.0.4
    bumpp: ^11.1.0
    eslint: ^10.5.0
    lint-staged: 16.4.0
    simple-git-hooks: ^2.13.1
    tsdown: 0.21.7
    typescript: ^6.0.3
  prod:
    '@antfu/eslint-config': ^9.0.0
    eslint-flat-config-utils: ^3.2.0
    jiti: ^2.7.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
allowBuilds:
  simple-git-hooks: true
